name: batch

on:
  schedule:
    # 10:00 AM on JST
    - cron: '0 1 * * *'
    # 02:00 PM on JST
    - cron: '0 5 * * *'
    # 06:00 PM on JST
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  batch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Run
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd src/
          python run.py
          cat num.txt > ../docs/index.html
          cp data.xlsx ../docs/output/data.xlsx

      - name: Set git settings & Commit changes
        run: |
          git config user.name "ssatocc"
          git config user.email "ssatocc@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "Auto commit" && git push)
