name: batch

on:
  workflow_dispatch:

jobs:
  batch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Run
        run: |
          cd src/
          python run.py
          echo "-- debug"
          ls
          echo "-- debug"
